#!/bin/bash

# Author : Andrew Hild
# Developed 02/2017
# Enjoy! SDG

SITE=$1
OUTPUT=$2
EXT=$3
tagre="<[^>]+>"
tmp=noot

if [ $# -gt 1 ];
then
touch $OUTPUT
touch $tmp
wget -O $OUTPUT $SITE
sed -r '/</,/>/ s/*//g' <$OUTPUT >$tmp
mv $tmp $OUTPUT
else
echo $SITE
wget $SITE
fi
