#!/bin/bash

# Author : Andrew Hild
# Developed 03/2018
# Enjoy! SDG

SITE=$1
OUTPUT=$2
EXT=$3
tagre="<[^>]+>\n*"
tmp=noot

if [ $# -gt 1 ];
then
touch $OUTPUT
touch $tmp
wget -O $OUTPUT $SITE
sed -r 's/'$tagre'//g' <$OUTPUT >$tmp
mv $tmp $OUTPUT
else
echo $SITE
wget $SITE
fi
